### ISSUE TITLE
How to prepare the raw data for disambiguation

### ISSUE THREAD

**Issue by abizerjafferjee** [PatentsView/PatentsView-Disambiguation#6]
Hi Monath,

I want to run the build for the assignee data but I don't understand how the sqlite database should be prepared and where to get the raw data from. I'd really appreciate your help.

**Comment by nmonath** [comment]
Hi, let me know if you have questions :)

**Comment by abizerjafferjee** [comment]
Hi @nmonath, thanks for the quick reply. Managed to get the granted data and started working through the code with that so decided to close the ticket. I haven't managed to find the pregranted data so if you could point me to that I'd appreciate it.

I'm sure I'll have more questions as I go through and may open an issue later.
